openapi: 3.0.0
info:
  title: RecollectionRealm
  version: 1.0.0
  description: >
    Personalized Journal Platform - Users can create, manage, and share
    multimedia-rich digital journals. Features include private/public sharing,
    collaboration, inheritance settings, and more.
servers:
  - url: http://localhost:8000
paths:
  /users:
    get:
      tags:
        - User
      summary: Retrieve a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - User
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
  /users/{id}:
    put:
      tags:
        - User
      summary: Update user information
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
    delete:
      tags:
        - User
      summary: Delete a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /journals:
    post:
      tags:
        - Journal
      summary: Create a new journal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - title
                - description
                - user_id
              properties:
                title:
                  type: string
                description:
                  type: string
                user_id:
                  type: integer
                tags:
                  type: array
                  items:
                    type: string
                categories:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Journal created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  journal:
                    type: object
    get:
      tags:
        - Journal
      summary: '    Retrieve all journals belonging to the authenticated user.'
      parameters:
              - in: query
                name: tags
                schema:
                  type: array
                  items:
                    type: string
              - in: query
                name: categories
                schema:
                  type: array
                  items:
                    type: string
      responses:
         '200':
          description: Journals retrived
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /journals/{journal_id}:
    put:
      tags:
        - Journal
      summary: Update journal details
      parameters:
        - in: path
          name: journal_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                description:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                categories:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Journal updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
    delete:
      tags:
        - Journal
      summary: Delete a journal
      parameters:
        - in: path
          name: journal_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Journal deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /journals/{journal_id}/collaborators:
    post:
      tags:
        - Journal
      summary: Invite a collaborator to journal
      parameters:
        - in: path
          name: journal_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                collaborator_email:
                  type: string
      responses:
        '200':
          description: Collaborator added
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /journals/{journal_id}/collaborators/{collaborator_id}:
    delete:
      tags:
        - Journal
      summary: Remove a collaborator
      parameters:
        - in: path
          name: journal_id
          required: true
          schema:
            type: integer
        - in: path
          name: collaborator_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Collaborator removed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /entries/{entry_id}/media:
    post:
      tags:
        - Entry
      summary: Add media to journal entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                media_type:
                  type: string
                  enum:
                    - photo
                    - video
                    - audio
                media_url:
                  type: string
      responses:
        '200':
          description: Media added
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  entry:
                    type: object
  /entries/{entry_id}/tags:
    put:
      tags:
        - Entry
      summary: Update entry tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Tags updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /journals/filter:
    get:
      tags:
        - Journal
      summary: Filter journals by tags/categories
      parameters:
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
        - in: query
          name: categories
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Journals filtered
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    created:
                      type: string
                      format: date-time
  /users/{user_id}/inheritor:
    post:
      tags:
        - User
      summary: Set an inheritor account
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                inheritor_email:
                  type: string
      responses:
        '200':
          description: Inheritor set
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /users/{user_id}/transfer-journals:
    post:
      tags:
        - User
      summary: Transfer journals to inheritor
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                inheritor_id:
                  type: integer
      responses:
        '200':
          description: Journals transferred
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
        creation_date:
          type: string
          format: date-time
        inheritor_id:
          type: integer
    Journal:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        privacy:
          type: integer
        password:
          type: string
        tags:
          type: string
        categories:
          type: string
        creation_date:
          type: string
          format: date-time
        user_id:
          type: integer
    Entry:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        privacy:
          type: integer
        creation_date:
          type: string
          format: date-time
        journal_id:
          type: integer


